<a href="https://colab.research.google.com/github/teerasitk/01205415/blob/main/Assignment08Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from typing import Tuple

In [4]:
day_per_year = 250

In [5]:
def getOptimumPortfolio(mu: np.ndarray, # average return vector assets
                       cov_mat: np.ndarray, # covarance matrix of assets
                        r_star: float) -> np.ndarray:
  """
    Find optimum portfolio with average target return at r_star
  """
  n = len(mu) # number of assets
  A = np.zeros((n + 1 + 1, n + 1 +1))
  b = np.zeros((n + 1 +1,))
  ones = np.ones((n,))
  A[:n, :n] = cov_mat
  A[:n, n] = - mu
  A[:n, n + 1] = -ones
  A[n, :n] = mu
  A[n+1, :n] = ones
  b[n] = r_star / day_per_year # change to daily target returns
  b[n + 1] = 1
  x = np.linalg.solve(A,b)
  w_opt = x[:n]
  return w_opt

In [15]:
R = np.array([[1,0.2, 0.5, 0.3],
              [0.2, 1, 0.7, 0.4],
              [0.5, 0.7, 1, 0.9],
              [0.3,0.4,0.9, 1]])
S = np.diag([0.12, 0.12, 0.15, 0.2])
Sigma = np.dot(S,np.dot(R,S))
print(R)
mu = np.array([0.02, 0.05, 0.02, 0.05])

[[1.  0.2 0.5 0.3]
 [0.2 1.  0.7 0.4]
 [0.5 0.7 1.  0.9]
 [0.3 0.4 0.9 1. ]]


In [16]:
risk_free_interests = [0.05, 0.1]
for r in risk_free_interests:
  w_opt = getOptimumPortfolio(mu=mu, cov_mat=Sigma, r_star=r)
  print(f"Optimum Portfolio for r = {r:0.2f} is: {w_opt}")

Optimum Portfolio for r = 0.05 is: [ 0.5147149  -0.03830472  1.1452851  -0.62169528]
Optimum Portfolio for r = 0.10 is: [ 0.51543021 -0.03547926  1.13790313 -0.61785408]
